# Generated by Django 5.0.1 on 2024-01-26 22:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_current_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlist_users',
            field=models.ManyToManyField(related_name='watchlist_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlisted_by', to='auctions.listing'),
        ),
    ]
