# Generated by Django 5.0.1 on 2024-01-26 22:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_watchlist_users_alter_user_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='watchlist_users',
            field=models.ManyToManyField(blank=True, related_name='watchlist_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
