# Generated by Django 5.0.1 on 2024-01-28 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listing_watchlist_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currently_winning', to=settings.AUTH_USER_MODEL),
        ),
    ]
